### ISSUE TITLE
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host hassio:8123 ssl:True

### ISSUE THREAD

**Issue by ayavilevich** [tmonck/clean_up_snapshots#12]
Integration tries to connect to hass over https even if the provided url specifies http.

Example:
``host: http://hassio:8123``

I believe the wrong logic is in:
https://github.com/tmonck/clean_up_snapshots/blob/master/custom_components/clean_backups/__init__.py#L92

The current logic means that if a hostname is used then ssl is forced. What was the original intention? Why differentiate between hostname and ip configurations in terms of ssl? Why not let the scheme alone determine the protocol?

A workaround right now is to specify the host using an IP.

P.S. nowhere does it say, nor there is an example, that the project will not work if "host" has a slash at the end. Would be preferred if it is specified, or if there is an example or if the code can work with both cases.

**Comment by tmonck** [comment]
I'll take a look at this tomorrow. I am away from a computer at the moment. I'll also work on providing the example requested.

**Comment by tmonck** [comment]
So I quickly double checked but line you referenced says that if it's not an ip address then to compare the scheme of the parsed url. Can you please provide the config for that you are using? Using the url you provided in the issue of 'http://hassio:8123' would result in a false value for ssl. I will look at getting an example up in the next day or so.

**Comment by ayavilevich** [comment]
Hey, thanks for looking at this so quickly.

The code right now is:

```
        # Check if the url is an ip address
        result = not isgoodipv4(urlPieces.netloc)

        # If url is not an ip address then check
        return result or urlPieces.scheme == "https"
```

so if url == 'http://hassio:8123'
then result = true
so return will not even evaluate the scheme. Maybe you means to use 'and' instead of 'or' or not use a 'not' with isgoodipv4.

Original intention is not clear.

**Comment by tmonck** [comment]
Ok I will dive deeper. I will also get a fix to support a trailing / on the base url as well. I'll link the PR to this issue so we can test.

**Comment by tmonck** [comment]
@ayavilevich I have opened a PR. If you want to take a peek. It will now have support for a trailing `/` as well I believe I have resolved the bug with the ssl issue. You were correct that It was force SSL when not using an IP Address which was a mistake great catch!

For a note the reason I have support of not always using the scheme of the URL is because there is times where someone may what to use the ip address with a scheme of `https` yet the cert is not valid for the IP Address and is actually for their public URL. To support this I added a new configuration value which can allow you to let an IP Address to validate the cert. I have default it to off.

**Comment by ayavilevich** [comment]
@tmonck I tried the branch.

Hostname works now. But I had to use "hassio.lan" as the host part in the url. You might want to add an example for that specifically. I supposed this is due to the way docker containers work.

Terminating '/' doesn't work. I also don't see any changes in the code to address that. Currently code will try to access: "http://hassio.lan:8123//api/hassio/snapshots" which will be invalid.

You might want to modify around ``hassio_url = '{}/api/hassio/'.format(conf.get(CONF_HOST))`` .

**Comment by tmonck** [comment]
Apparently I blew away the change I had for the trailing / I'll push up that fix now. I'll also add the example using lan and mention this issue as a reference. Not sure why it would require the `.lan` portion.

**Comment by tmonck** [comment]
PR is updated @ayavilevich if you wouldn't mind trying once more. If the trailing slash is working I'll get a release and some release notes together.

**Comment by ayavilevich** [comment]
@tmonck hey, np.

Tested, works ok now with and without back slash.
