### ISSUE TITLE
Error on new HA 2021.6

### ISSUE THREAD

**Issue by sagitt** [tmonck/clean_up_snapshots#18]
<Integration tmonck/clean_up_snapshots> Could not read manifest.json [Expecting ',' delimiter: line 7 column 23 (char 222)]

with last addon version.

**Comment by inverse** [comment]
Fixed in https://github.com/tmonck/clean_up_snapshots/pull/19

**Comment by inverse** [comment]
@sagitt you can manually modify the `.` on line 7 in the `manifest.json` to unblock yourself until a new release is done.

**Comment by sagitt** [comment]
> @sagitt you can manually modify the `.` on line 7 in the `manifest.json` to unblock yourself until a new release is done.

well, thanks.

when will be released?

**Comment by inverse** [comment]
@sagitt whenever the owner has time to do so. I suspect within 1h.

**Comment by sagitt** [comment]
> @sagitt whenever the owner has time to do so. I suspect within 1h.

thanks!
i already fixed it for my installation :)

**Comment by tmonck** [comment]
Thanks @inverse PR is merged.

**Comment by tmonck** [comment]
Release 0.8.1 pushed
