### ISSUE TITLE
Errors in logs

### ISSUE THREAD

**Issue by ScrewLooseDan** [tmonck/clean_up_snapshots#23]
I manually installed this integration (don't use HACS, just copying the custom_component folder), so perhaps this issue is self-inflicted.  But, I figured I would ask here is these errors I'm seeing in my logs make any sense and if there is an easy fix or not.

I've upgraded recently to the latest version (0.8.2) and see the following in my logs upon a restart:

```
Logger: homeassistant.helpers.integration_platform
Source: loader.py:535
First occurred: 12:03:13 PM (5 occurrences)
Last logged: 12:03:13 PM

Unexpected error importing clean_up_snapshots_service/recorder.py
Unexpected error importing clean_up_snapshots_service/group.py
Unexpected error importing clean_up_snapshots_service/media_source.py
Unexpected error importing clean_up_snapshots_service/system_health.py
Unexpected error importing clean_up_snapshots_service/logbook.py
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 33, in _process
    platform = integration.get_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 530, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 535, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.clean_backups.recorder'
```

The clean_up_snapshots_service works as expected and I don't any errors while calling the service. Just curious if there is a way I could clean these up in my logs?

**Comment by tmonck** [comment]
Let me see. I wasn't seeing this in my instance of homeassistant so I need to see if I can replicate.

**Comment by ScrewLooseDan** [comment]
I wanted to be sure it wasn't something with my HA instance.  So, I just made a new test Home Assistant instance and was able to reproduce it.

- Used VirtualBox to create a new base HA instance. (followed instructions [here](https://www.home-assistant.io/installation/linux))
- Added Community SSH & Web Terminal add-on
- SSH'd to new instance and used following commands:
  - git clone https://github.com/tmonck/clean_up_snapshots.git
  - mkdir /config/custom_components/
  - cp -r clean_up_snapshots/custom_components/clean_backups /config/custom_components/
- Created long lived token
- Added following to configuration.yaml
  - clean_up_snapshots_service:
  -  host: http://<ip_addess:8123/
  -  token: <long lived token>
  -  number_of_snapshots_to_keep: 3

This produced the same errors as on my production Home Assistant:
```
Logger: homeassistant.helpers.integration_platform
Source: loader.py:535
First occurred: 10:06:38 AM (5 occurrences)
Last logged: 10:06:38 AM

Unexpected error importing clean_up_snapshots_service/recorder.py
Unexpected error importing clean_up_snapshots_service/media_source.py
Unexpected error importing clean_up_snapshots_service/system_health.py
Unexpected error importing clean_up_snapshots_service/logbook.py
Unexpected error importing clean_up_snapshots_service/group.py
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 33, in _process
    platform = integration.get_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 530, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 535, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.clean_backups.recorder'
```

I understand if you only want to support HACS installs, and I'm okay with that.  But since I've installed other custom integrations the same way and not had an issue, I figured I would ask.

**Comment by ScrewLooseDan** [comment]
I figured it out.  I installed HACS on my test instance and saw that the name of the folder for the custom component is `clean_up_snapshots_service`, not as the folder structure in git has it - `clean_backups`.

On my production HA server I simply did the following, followed by a restart, and no more errors.

`mv /config/custom_components/clean_backups/ /config/custom_components/clean_up_snapshots_service`

**Comment by tmonck** [comment]
I'll update the documentation to reflect this.
