### ISSUE TITLE
Update needed to address /backups change

### ISSUE THREAD

**Issue by 715Steve** [tmonck/clean_up_snapshots#24]
In relation to this:

https://developers.home-assistant.io/blog/2021/08/24/supervisor_update/

It appears to be causing an issue now. Perhaps the old /snapshots has now been deleted?

**Comment by tmonck** [comment]
Actively working on this hoping to have a fix by end of day today.

**Comment by tmonck** [comment]
I have released version 0.9.0 which has the changes necessary to call the new endpoint. @715Steve create a new issue if you continue to have issues.
