### ISSUE TITLE
Not working since 2023.3.3?

### ISSUE THREAD

**Issue by SupremeSports** [tmonck/clean_up_snapshots#29]
Hi, the integration stopped working. According to other API issues I've seen across the internet, it looks like it's since 2023.3.3 and going back to 2023.3.1 fixes the issue. Apparently it's related to long-lived tokens. Might be related to [#89919](https://github.com/home-assistant/core/issues/89919)

**Comment by SupremeSports** [comment]
Error message when calling automation to clean:
`Logger: custom_components.clean_up_snapshots_service
Source: custom_components/clean_up_snapshots_service/__init__.py:49
Integration: Clean up your snapshots ([documentation](https://github.com/tmonck/clean_up_snapshots))
First occurred: 11:40:18 AM (1 occurrences)
Last logged: 11:40:18 AM

Client error on calling get snapshots
Traceback (most recent call last):
  File "/config/custom_components/clean_up_snapshots_service/__init__.py", line 49, in async_get_snapshots
    resp = await session.get(hassio_url + BACKUPS_URL_PATH, headers=headers, ssl=shouldVerifySsl(hassio_url))
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 643, in _request
    resp.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1005, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 401, message='Unauthorized', url=URL('http://192.168.1.10:8123/api/hassio/ingress/backups')`

**Comment by tmonck** [comment]
Thanks for posting this, I completely spaced on this in my instance. I am actively debugging and will have a working version soon.

**Comment by tmonck** [comment]
Looks like this will take some time https://github.com/home-assistant/core/issues/90400 there was a security vulnerability that home assistant closed and caused this issue. I'm going to keep this open while waiting for a fix.

**Comment by xabileiro** [comment]
Same issue

**Comment by tmonck** [comment]
I have merge the code from @DaftHonk and published a new release.

**Comment by tmonck** [comment]
I have confirm the fix has been applied with the latest version 0.10.0
