### ISSUE TITLE
The 'clean_up_snapshots_service' option near /config/configuration.yaml:1 is deprecated

### ISSUE THREAD

**Issue by sddgit** [tmonck/clean_up_snapshots#45]
In 2023.5.4, using latest version of the service:
```
This error originated from a custom integration.

Logger: custom_components.clean_up_snapshots_service
Source: helpers/config_validation.py:863 
Integration: Clean up snapshots service (documentation, issues) 
First occurred: 18:17:38 (1 occurrences) 
Last logged: 18:17:38

The 'clean_up_snapshots_service' option near /config/configuration.yaml:1 is deprecated, please remove it from your configuration```

**Comment by tmonck** [comment]
This is expected the latest release migrated to using config flow. You can now update the value in device and integrations page l.

**Comment by sddgit** [comment]
Thank you for the reply. I’m not familiar with what config flow actually means 😉. Am I supposed to remove all reference to the service from my configuration.yaml then, and just submit the required value by configuring the integration? Sorry for the basic question…

**Comment by tmonck** [comment]
No worries at all. 

I've already migrated the data to the new location that is needed so you wouldn't need to do anything beyond removing it from your configuration.yaml.

 If you wanted to update the default value you no longer have to update the configuration.yaml and restart. You can just go to the integration on devices and services and click configure. If you were to do this currently you should see the value that existed in your configuration.yaml.

Let me know if you have any problems or have any other questions.

**Comment by sddgit** [comment]
Thank you - all cleaned up!

**Comment by sddgit** [comment]
Closed.
