### ISSUE TITLE
Unable to remove snapshots after 0.4

### ISSUE THREAD

**Issue by gateriderz** [tmonck/clean_up_snapshots#8]
Hi,
On v0.4, I got an error when i call the service to cleanup snapshots and the snapshots are still there.

I reverted back to 0.3, which works great for me.  I use node-red to call the service at 01:00 am, so i only noticed it the next day.

I don’t mind to update it again and send you logs if you want to take a look at the error.

Thanks

**Comment by tmonck** [comment]
I updated and was waiting for it to execute. Let me take a look.

**Comment by tmonck** [comment]
@gateriderz I am unable to get an error could you provide me what logs if possible? Also are you using an IP address for your host variable?

**Comment by gateriderz** [comment]
> @gateriderz I am unable to get an error could you provide me the logs if possible? Also are you using an IP address for your host variable?

yes i am using a variable from my secrets to add the host ip  http://{IP}:8123
I deployed v.04 and changed the urlPieces as requested and its working.
Thank you

**Comment by tmonck** [comment]
Awesome. I'm going to merge in my changes. That should resolve the issue so that you don't need to manually make the changes.

**Comment by tmonck** [comment]
Release 0.5 has the changes. Thank you for reporting the issue @gateriderz .

**Comment by gateriderz** [comment]
> Awesome. I'm going to merge in my changes. That should resolve the issue so that you don't need to manually make the changes.

perfect. thank you.  Already updated via HACS.
Have a good one and great utility.
